apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
  labels:
    app: java-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
      - name: java-service
        image: <id_detucuenta>.dkr.ecr.us-east-1.amazonaws.com/java-service:{{TAG}}
        env:
        - name: environment
          value: "ci"
        - name: LOG_LEVEL_SYSTEM
          value: "INFO"
        - name: LOG_LEVEL_BUSINESS
          value: "ERROR"
        - name: LOGS_FOLDER
          value: "/var/log/java-service"
        ports:
        - containerPort:
        resources:
          limits:
            cpu: 200m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always
