apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-service
  name: java-service
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 8031
  selector:
    app: java-service
status:
  loadBalancer: {}
